"""Updating Candidate.

Revision ID: 22eae66ad2f3
Revises: 84a38ccb6049
Create Date: 2023-07-11 17:27:04.125265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22eae66ad2f3'
down_revision = '84a38ccb6049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('party')

    # ### end Alembic commands ###
