"""Updating Candidate 2.

Revision ID: 3afeb8014466
Revises: 22eae66ad2f3
Create Date: 2023-07-11 18:14:47.887736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afeb8014466'
down_revision = '22eae66ad2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filing_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('filing_date')

    # ### end Alembic commands ###
