"""Vote count precinct uniue.

Revision ID: 6711f7ac3cf9
Revises: d59f1c519ece
Create Date: 2023-07-12 19:38:14.487015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6711f7ac3cf9'
down_revision = 'd59f1c519ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_count', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['precinct'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_count', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
