# Generated by Django 5.0.4 on 2024-04-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBorrower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studid', models.TextField(max_length=15, unique=True)),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedHist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_date', models.DateField()),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olms.studentborrower', to_field='studid')),
            ],
        ),
    ]
