"""Drop columns migration.

Revision ID: ba77d2b6828a
Revises: bce251416eb5
Create Date: 2024-05-31 08:29:25.231012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba77d2b6828a'
down_revision = 'bce251416eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complainantId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('complaint_ticketId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'complainant', ['complainantId'], ['id'])
    
    with op.batch_alter_table('complainant', schema=None) as batch_op:
        batch_op.drop_constraint('complainant_ticketId_key', type_='unique')
        batch_op.drop_column('ticketId')
       
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('complaint_ticketId_fkey', 'complainant', ['ticketId'], ['ticketId'])
        batch_op.drop_column('complainantId')

    with op.batch_alter_table('complainant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticketId', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('complainant_ticketId_key', ['ticketId'])

    # ### end Alembic commands ###
