"""Initial migration.

Revision ID: bce251416eb5
Revises: 
Create Date: 2024-05-03 14:23:37.970054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce251416eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complainant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('middlename', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('ticketId', sa.String(length=55), nullable=False),
    sa.Column('date_registered', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticketId')
    )
    op.create_table('complaint_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketId', sa.String(), nullable=False),
    sa.Column('catid', sa.Integer(), nullable=False),
    sa.Column('ctype', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catid'], ['category.id'], ),
    sa.ForeignKeyConstraint(['ctype'], ['complaint_type.id'], ),
    sa.ForeignKeyConstraint(['ticketId'], ['complainant.ticketId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compid', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['compid'], ['complaint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_details')
    op.drop_table('complaint')
    op.drop_table('complaint_type')
    op.drop_table('complainant')
    op.drop_table('category')
    # ### end Alembic commands ###
