"""empty message

Revision ID: 9eafa601a7db
Revises: 
Create Date: 2023-06-08 06:51:46.327352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eafa601a7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('middlename', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('mobile', sa.String(length=45), nullable=True),
    sa.Column('date_registered', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complainant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('middlename', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('date_registered', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('catid', sa.Integer(), nullable=False),
    sa.Column('ctype', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catid'], ['category.id'], ),
    sa.ForeignKeyConstraint(['cid'], ['complainant.id'], ),
    sa.ForeignKeyConstraint(['ctype'], ['complaint_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compid', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['compid'], ['complaint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_details')
    op.drop_table('complaint')
    op.drop_table('complainant')
    op.drop_table('admin')
    op.drop_table('login')
    op.drop_table('complaint_type')
    op.drop_table('category')
    # ### end Alembic commands ###
