"""Initial migration.

Revision ID: 45cde1ffaf73
Revises: 
Create Date: 2023-12-01 16:53:26.202256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cde1ffaf73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empid', sa.String(length=12), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('midname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empid')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empid', sa.String(length=12), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('midname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empid')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('midname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('date_registered', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patientid')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketid', sa.String(length=20), nullable=False),
    sa.Column('patientid', sa.Integer(), nullable=False),
    sa.Column('docid', sa.String(length=12), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('date_scheduled', sa.Date(), nullable=False),
    sa.Column('time_scheduled', sa.Time(), nullable=False),
    sa.Column('consult_hrs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['docid'], ['doctor.empid'], ),
    sa.ForeignKeyConstraint(['patientid'], ['patient.patientid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docid', sa.String(length=12), nullable=False),
    sa.Column('patientid', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.String(length=500), nullable=False),
    sa.Column('resolution', sa.String(length=500), nullable=False),
    sa.Column('date_submitted', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['docid'], ['doctor.empid'], ),
    sa.ForeignKeyConstraint(['patientid'], ['patient.patientid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paymentid', sa.String(length=50), nullable=False),
    sa.Column('patientid', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('discount', sa.Double(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_released', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patientid'], ['patient.patientid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docid', sa.String(length=12), nullable=False),
    sa.Column('adminid', sa.String(length=12), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('date_approved', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['adminid'], ['administrator.empid'], ),
    sa.ForeignKeyConstraint(['docid'], ['doctor.empid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('payment')
    op.drop_table('diagnosis')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('administrator')
    op.drop_table('login')
    # ### end Alembic commands ###
